services:
  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/config.yml
    configs:
    - source: promtail.yml
      target: /etc/promtail/config.yml
    volumes:
    - /var/lib/docker:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    expose:
    - 3100/tcp

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    expose:
    - 8080/tcp

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    expose:
    - 9090/tcp
    configs:
    - source: prometheus.yml
      target: /etc/prometheus/prometheus.yml

  jsonnet:
    image: ghcr.io/lyatanski/grafonnet
    command:
    - sh
    - -exc
    - |
      for jsonnet in /dash/*.jsonnet; do
        jsonnet $$jsonnet -o /board/$$(basename $$jsonnet .jsonnet).json
      done
    configs:
    - source: stat.jsonnet
      target: /dash/stat.jsonnet
    - source: log.jsonnet
      target: /dash/log.jsonnet
    - source: rtp.jsonnet
      target: /dash/rtp.jsonnet
    - source: ims.jsonnet
      target: /dash/ims.jsonnet
    volumes:
    - dash:/board

  grafana:
    image: grafana/grafana
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /usr/share/grafana/dashboards/stat.json
    configs:
    - source: datasources.yml
      target: /etc/grafana/provisioning/datasources/ds.yaml
    - source: dashboards.yml
      target: /etc/grafana/provisioning/dashboards/ds.yaml
    volumes:
    - dash:/usr/share/grafana/dashboards
    depends_on:
      jsonnet:
        condition: service_completed_successfully
    ports:
    - 3000:3000


configs:
  promtail.yml:
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      positions:
        filename: /tmp/positions.yaml
      clients:
      - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
      - job_name: system
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 5s
        relabel_configs:
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container'
        #pipeline_stages:

  datasources.yml:
    content: |
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        orgId: 1
        uid: loki
        url: http://loki:3100
        access: proxy
        basicAuth: false
        editable: false
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus:9090
        access: proxy
        basicAuth: false
        editable: false

  dashboards.yml:
    content: |
      apiVersion: 1
      providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 3600
        options:
          path: /etc/dashboards

  stat.jsonnet:
    content: |
      local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
      local ds = 'prometheus';

      local stat(title, expr, pos, unit=null) =
        g.panel.stat.new(title)
        + g.panel.stat.queryOptions.withDatasource('prometheus', ds)
        + g.panel.stat.queryOptions.withTargets([g.query.prometheus.new(ds, expr)])
        + g.panel.stat.panelOptions.withGridPos(pos.h, pos.w, pos.x, pos.y)
        + g.panel.stat.panelOptions.withTransparent()
        + if unit == null then {} else g.panel.stat.standardOptions.withUnit(unit);

      local ts(title, expr, pos, unit) =
        g.panel.timeSeries.new(title)
        + g.panel.timeSeries.queryOptions.withDatasource('prometheus', ds)
        + g.panel.timeSeries.queryOptions.withTargets([
            g.query.prometheus.new(ds, expr)
            + g.query.prometheus.withLegendFormat('{{name}}')
          ])
        + g.panel.timeSeries.panelOptions.withGridPos(pos.h, pos.w, pos.x, pos.y)
        + g.panel.timeSeries.standardOptions.withUnit(unit);

      g.dashboard.new('stat')
      + g.dashboard.withDescription('container resource monitoring')
      + g.dashboard.time.withFrom('now-6h')
      + g.dashboard.withRefresh('5s')
      + g.dashboard.graphTooltip.withSharedCrosshair()
      + g.dashboard.withPanels([
        stat('Running containers', 'count(time() - container_last_seen{name!=\'\'} < 30)',              {h: 3, w: 8, x: 0,  y: 0}),
        stat('Total Mem Usage',    'sum(container_memory_usage_bytes{name!=\'\'})',                     {h: 3, w: 8, x: 8,  y: 0}, 'bytes'),
        stat('Total CPU Usage',    'sum(rate(container_cpu_user_seconds_total{name!=\'\'}[5m]) * 100)', {h: 3, w: 8, x: 16, y: 0}, 'percent')
        + g.panel.stat.standardOptions.withMin(0)
        + g.panel.stat.standardOptions.withMax(100),

        ts('CPU Usage',  'rate(container_cpu_user_seconds_total{name!=\'\'}[5m]) * 100',                {h: 7, w: 24, x: 0,  y: 3 }, 'percent'),
        ts('Mem Usage',  'container_memory_usage_bytes{name!=\'\'}',                                    {h: 7, w: 24, x: 0,  y: 10}, 'bytes'),
        ts('Network Rx', 'irate(container_network_receive_bytes_total{name!=\'\'}[5m])',                {h: 7, w: 12, x: 0,  y: 17}, 'Bps'),
        ts('Network Tx', 'irate(container_network_transmit_bytes_total{name!=\'\'}[5m])',               {h: 7, w: 12, x: 12, y: 17}, 'Bps'),
      ])

  ims.jsonnet:
    content: |
      local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
      local ds = 'prometheus';

      g.dashboard.new('IMS')
      + g.dashboard.withDescription('IMS overview')
      + g.dashboard.time.withFrom('now-6h')
      + g.dashboard.withRefresh('5s')
      + g.dashboard.withPanels([
          g.panel.stat.new('registrations')
          + g.panel.stat.panelOptions.withGridPos(h=6, w=6, x=0, y=0)
          + g.panel.stat.queryOptions.withTargets([
            g.query.prometheus.new(ds, 'kamailio_ims_registrar_scscf_accepted_regs')
            ]),
          g.panel.stat.new('calls')
          + g.panel.stat.panelOptions.withGridPos(h=6, w=6, x=6, y=0)
          + g.panel.stat.queryOptions.withTargets([
            g.query.prometheus.new(ds, 'kamailio_dialog_ng_active{job="scscf"}')
            ]),
          g.panel.stat.new('failed')
          + g.panel.stat.panelOptions.withGridPos(h=6, w=6, x=12, y=0)
          + g.panel.stat.queryOptions.withTargets([
            g.query.prometheus.new(ds, 'kamailio_ims_registrar_scscf_rejected_regs')
            ]),
      ])

  log.jsonnet:
    content: |
      local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
      local ds = 'loki';
      local var = g.dashboard.variable;

      g.dashboard.new('logs')
      + g.dashboard.withDescription('logs overview')
      + g.dashboard.time.withFrom('now-6h')
      + g.dashboard.withRefresh('5s')
      + g.dashboard.withVariables([
        var.query.new('container', 'label_values(container)')
        + var.query.withDatasource('loki', ds)
        + var.query.generalOptions.withLabel('Container')
        + var.query.refresh.onLoad()
        + var.query.withSort(5)
        + var.query.selectionOptions.withMulti()
        + var.query.selectionOptions.withIncludeAll(customAllValue='.+'),
        var.textbox.new('search')
        + var.textbox.generalOptions.withLabel('Search'),
      ])
      + g.dashboard.withPanels([
        g.panel.logs.new('')
        + g.panel.logs.panelOptions.withGridPos(h=22, w=24, x=0, y=0)
        + g.panel.logs.panelOptions.withTransparent()
        + g.panel.logs.queryOptions.withDatasource('loki', ds)
        + g.panel.logs.queryOptions.withTargets([
          g.query.loki.new(ds, '{container=~"$$container"} |~ "(?i)$$search"')
        ]),
      ])

  rtp.jsonnet:
    content: |
      local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
      local ds = 'prometheus';
      
      local stat(title, expr, x, y, w, h, unit=null) =
        g.panel.stat.new(title)
        + g.panel.stat.queryOptions.withDatasource('prometheus', ds)
        + g.panel.stat.queryOptions.withTargets([g.query.prometheus.new(ds, expr)])
        + g.panel.stat.options.withGraphMode('area')
        + g.panel.stat.panelOptions.withGridPos(h=h, w=w, x=x, y=y)
        + if unit == null then {} else g.panel.stat.standardOptions.withUnit(unit);

      local gauge(title, expr, x, y) =
        g.panel.gauge.new(title)
        + g.panel.gauge.queryOptions.withDatasource('prometheus', ds)
        + g.panel.gauge.queryOptions.withTargets([g.query.prometheus.new(ds, expr)])
        + g.panel.gauge.panelOptions.withGridPos(h=5, w=3, x=x, y=y);

      local tsTarget(reason, legend) =
        g.query.prometheus.new(ds, 'rtpengine_closed_sessions_total{reason="%s", job="$job"}' % reason)
        + g.query.prometheus.withLegendFormat(legend);

      g.dashboard.new('RTP')
      + g.dashboard.withDescription('A general view of RTPEngine.')
      + g.dashboard.time.withFrom('now-6h')
      + g.dashboard.withRefresh('5s')
      + g.dashboard.withPanels([
        gauge('Foreign Sessions',     'rtpengine_sessions{type="foreign", job="$$job"}', 0, 0),
        gauge('Own Sessions',         'rtpengine_sessions{type="own", job="$$job"}',     3, 0),
        gauge('Transcoding Sessions', 'rtpengine_transcoded_media{job="$$job"}',         6, 0),

        g.panel.timeSeries.new('Total Closed Sessions')
        + g.panel.timeSeries.queryOptions.withDatasource('prometheus', ds)
        + g.panel.timeSeries.queryOptions.withTargets([
          tsTarget('rejected',         'Rejected'),
          tsTarget('timeout',          'Timeout'),
          tsTarget('silent_timeout',   'Silent Timeout'),
          tsTarget('final_timeout',    'Final Timeout'),
          tsTarget('offer_timeout',    'Offer Timeout'),
          tsTarget('terminated',       'Terminated'),
          tsTarget('force_terminated', 'Force Timeout'),
        ])
        + g.panel.timeSeries.panelOptions.withGridPos(h=8, w=24, x=0, y=5),

        stat('Uptime',                'rtpengine_uptime_seconds{job="$$job"}',            10, 0,  7, 5, 's'),
        stat('Total sessions',        'rtpengine_sessions_total{job="$$job"}',            17, 0,  7, 5),
        stat('Total Relayed Packets', 'rtpengine_packets_total{type="userspace"}',        0,  13, 6, 5),
        stat('Total Relayed Bytes',   'rtpengine_bytes_total{type="userspace"}',          6,  13, 4, 5, 'decbytes'),
        stat('Total Relayed Errors',  'rtpengine_packet_errors_total{type="userspace"}',  10, 13, 6, 5),
        stat('Zero packet streams',   'rtpengine_zero_packet_streams_total{job="$$job"}', 16, 13, 4, 5),
        stat('Total 1-way streams',   'rtpengine_one_way_sessions_total{job="$$job"}',    20, 13, 4, 5),
      ])

  prometheus.yml:
    content: |
      global:
        scrape_interval: 10s
      scrape_configs:
      - job_name: cadvisor
        static_configs:
        - targets:
          - cadvisor:8080
      - job_name: pcscf
        honor_timestamps: false
        static_configs:
        - targets:
          - pcscf:9090
      - job_name: icscf
        honor_timestamps: false
        static_configs:
        - targets:
          - icscf:9090
      - job_name: scscf
        honor_timestamps: false
        static_configs:
        - targets:
          - scscf:9090
      - job_name: rtpengine
        honor_timestamps: false
        static_configs:
        - targets:
          - rtpengine:9090
volumes:
  dash:
